### ISSUE TITLE
"Compatible with ITS"™

### ISSUE THREAD

**Issue by larsbrinkhoff** [Isysxp/Tek-Term#1]
FYI, this emulator works fine with ITS' `:tctyp tek` terminal type and Macsyma function plotting.

**Comment by Isysxp** [comment]
Dear Lars,

 Thanks for looking at this. I have kept a bit quiet about this project as it rather collided with Rene Richardz's version which I note is in the ITS build.
 It is a sort of 'reasonable' app. The main difference being that it uses an ancient bitmap font rather than truetype. Rather more genuine!!
Still needs a bit of work.

In the meanwhile, I am glad you called. I am just trying out the ITS c compiler.
I have a file CT C in a directory CTEST

NB There is an error in my tiny file. printf is not in clib as far as I can see ... should use cprint(cout,"hello world");

int main()
{
        printf("hello world\r\n");
}


Nonetheless, when I type :cc -g ctest;ct c
the compiler seems to start but nothing happens until I press ^G (I found this out by luck)
eg
*:cc -g ctest;ct c
ctest;ct:


 -- ^G --
*
Any suggestions as it should at least compile to generate a MIDAS file with an expected error at link time (no printf) from STINKR?
The :INFO CC stuff is quite useful but does not help me at this point.

Regards, Ian.

________________________________

**Comment by larsbrinkhoff** [comment]
The C compiler and associated tools are a bit strange.  They were made by Alan Snyder after coming back to MIT from Bell Labs, and he tried to make a pseudo Unix environment for ITS.  Thus the filename syntax isn't that of ITS, but of Unix.  Try this:

```
:cc -g ctest/ct.c
```

It should leave a file CTEST; CT STK which is a REL(ocatable) file.  You need to use STINKR to link it with the C library.  See the build scripts for examples.
